return {
    BanMessage = 'You have been permanently banned from the game. If you believe this is a mistake contact us through our communications server.',

    ChatTags = {
        Users = {
            [256584577] = { Value = '[CH]', Color = '#b9ff80' }
        },

        Groups = {
            [33822371] = {
                { RankIds = { 252 },  Value = '[ARC]', Color = '#94db8a' },
                { RankIds = { 255 }, Value = '[King]', Color = '#000000' }
            }
        }
    },

    RedactedNames = {
        Users = {
            [256584577] = { RedactMessage = '[UrMom]:' }
        },

        Groups = {
            [33822371] = { RedactMessage = '[Guardsman]:', RankIds = { 50, 55, 100 } }
        }
    }
}
